# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from

# Site settings
title: "Seokju Hong"
description: "Yet another [`gosu`](https://en.wikipedia.org/wiki/Gosu) wannabe developer, M.S. Candidate @ KAIST CS"
email: 'seokju.hong _at_ kaist.ac.kr'
#blog logo
logo: "/assets/images/portrait.jpg"
# blog cover
cover: "/assets/images/banner.jpg"

authors:
  suckzo_o:
    name: "Seokju Hong"
    image: "/assets/images/portrait.jpg"
  # 2:
  #   name:
  #   image:

paginate: 5

url: "http://suckzoo.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@suckzo_p'

#fill in disqus shortname to use disqus
disqus: 'seokjuhong'

timezone: Asia/Seoul

# social icons and sharing options
social:

  - icon: facebook
    url: http://fb.me/suckzoo
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: twitter
    url: https://twitter.com/suckzo_p
    desc: Connect with me twitter
    share_url:
    share_title:
    share_link:

  - icon: github
    url:  https://github.com/suckzoo
    desc: Our GitHub
    share_url:
    share_title:
    share_link:
